To much changes (#6)
* PoC

* Update forces_example.v

* Update forces_example.v

* hummm

At least a tried

* tout cassé

* Revert "tout cassé"

This reverts commit d1fba9e2c53a3655a7f6073774bbb12473a1f3d8.

* Revert "hummm"

This reverts commit 937f9f5562238446c5f4b0bef527695693ec56bf.

* C error

 error: cannot convert 'struct math__vec__Vec2_T_f64 *' to 'struct math__vec__Vec2_T_f64'

* Doesn't break

* Better working

* dt

* Pause

* Kind of work ? IG ?

* fact

* Same probleme

* dt

* Corner

* Keep change

* V to change the render

* exteriors

* touch

* move

* Issue because of front being update first

* Surfaces

* Update forces_example.v

* Need a fix from gg_plot

* fix found it needs a f32()

* comment other renderring methodes

* News rendering

* angles for the head

* fix rendering

* better

* Update graphic_debug.v

* Update graphic_debug.v

* filled_render change location

* front for snake

* Update snake_example.v